variables:
  DOTNET_SDK_VERSION: '2.2.105' # see on when you can upgrade https://github.com/cake-build/cake/issues/2497
  DOTNET_PACKAGE_TYPE: 'sdk'
  RUBY_VERSION: '2.5'
  global_variable: value    # this is available to all jobs

jobs:

  steps:
  - bash: echo $(global_variable)
  - bash: echo $GLOBAL_VARIABLE

- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS 10.13'
    installRuby: 'false'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'VS2017-Win2016'

